public enum Roman_numeral {
    I	("I"),
    II	("II"),
    III	("III"),
    IV	("IV"),
    V	("V"),
    VI	("VI"),
    VII	("VII"),
    VIII	("VIII"),
    IX	("IX"),
    X	("X"),
    XI	("XI"),
    XII	("XII"),
    XIII	("XIII"),
    XIV	("XIV"),
    XV	("XV"),
    XVI	("XVI"),
    XVII	("XVII"),
    XVIII	("XVIII"),
    XIX	("XIX"),
    XX	("XX"),
    XXI	("XXI"),
    XXII	("XXII"),
    XXIII	("XXIII"),
    XXIV	("XXIV"),
    XXV	("XXV"),
    XXVI	("XXVI"),
    XXVII	("XXVII"),
    XXVIII	("XXVIII"),
    XXIX	("XXIX"),
    XXX	("XXX"),
    XXXI	("XXXI"),
    XXXII	("XXXII"),
    XXXIII	("XXXIII"),
    XXXIV	("XXXIV"),
    XXXV	("XXXV"),
    XXXVI	("XXXVI"),
    XXXVII	("XXXVII"),
    XXXVIII	("XXXVIII"),
    XXXIX	("XXXIX"),
    XL	("XL"),
    XLI	("XLI"),
    XLII	("XLII"),
    XLIII	("XLIII"),
    XLIV	("XLIV"),
    XLV	("XLV"),
    XLVI	("XLVI"),
    XLVII	("XLVII"),
    XLVIII	("XLVIII"),
    XLIX	("XLIX"),
    L	("L"),
    LI	("LI"),
    LII	("LII"),
    LIII	("LIII"),
    LIV	("LIV"),
    LV	("LV"),
    LVI	("LVI"),
    LVII	("LVII"),
    LVIII	("LVIII"),
    LIX	("LIX"),
    LX	("LX"),
    LXI	("LXI"),
    LXII	("LXII"),
    LXIII	("LXIII"),
    LXIV	("LXIV"),
    LXV	("LXV"),
    LXVI	("LXVI"),
    LXVII	("LXVII"),
    LXVIII	("LXVIII"),
    LXIX	("LXIX"),
    LXX	("LXX"),
    LXXI	("LXXI"),
    LXXII	("LXXII"),
    LXXIII	("LXXIII"),
    LXXIV	("LXXIV"),
    LXXV	("LXXV"),
    LXXVI	("LXXVI"),
    LXXVII	("LXXVII"),
    LXXVIII	("LXXVIII"),
    LXXIX	("LXXIX"),
    LXXX	("LXXX"),
    LXXXI	("LXXXI"),
    LXXXII	("LXXXII"),
    LXXXIII	("LXXXIII"),
    LXXXIV	("LXXXIV"),
    LXXXV	("LXXXV"),
    LXXXVI	("LXXXVI"),
    LXXXVII	("LXXXVII"),
    LXXXVIII	("LXXXVIII"),
    LXXXIX	("LXXXIX"),
    XC	("XC"),
    XCI	("XCI"),
    XCII	("XCII"),
    XCIII	("XCIII"),
    XCIV	("XCIV"),
    XCV	("XCV"),
    XCVI	("XCVI"),
    XCVII	("XCVII"),
    XCVIII	("XCVIII"),
    XCIX	("XCIX"),
    C	("C");

    private String num;
    Roman_numeral(String num){
        this.num = num;
    }
    @Override
    public String toString(){
        return num;
    }
    public static String find(int pos){//переводит арабское число в римское и возвращает его в виде строки
        for (Roman_numeral rn:
             Roman_numeral.values()) {
            if (rn.ordinal()==pos-1){
                return rn.toString();
            }
        }
        return "0";
    }
}
